---
- name: Download release zabbix
  get_url:
    url: https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian11_all.deb
    dest: /tmp/zabbix-release.deb

- name: Install a .deb package
  apt:
    deb: /tmp/zabbix-release.deb

- name: update cache
  apt:
    update_cache: yes

- name: install zabbix
  apt:
    name:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-agent

- name: grant all privileges
  shell: mysql -uroot -proot -e "grant all privileges on zabbix.* to zabbix@localhost"

- name: set global log_bin_trust_function_creators
  shell: mysql -uroot -proot -e "set global log_bin_trust_function_creators = 1"

- name: import database
  shell: zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -u zabbix -pzabbix zabbix

- name: copy zabbix-server.conf
  template:
    src: zabbix_server.conf
    dest: /etc/zabbix/zabbix_server.conf

- name: Adicionando Idioma Ingles ao locales
  shell: echo "en_US.UTF-8 UTF-8" > /etc/locale.gen

- name: Adicionando Idioma Português ao locales
  shell: echo "pt_BR.UTF-8 UTF-8" > /etc/locale.gen

- name: Atualizando o Locale
  shell: locale-gen

- name: start service zabbix-server
  service:
    name: zabbix-server
    state: restarted
    enabled: yes

- name: start service zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes

- name: start service apache2
  service:
    name: apache2
    state: restarted
    enabled: yes

